name: Reboot command via SSH every 3 hour!
on:
  schedule:
    - cron: '0 */3 * * *' # runs every 3 hours
  workflow_dispatch:
env:
  SEGFAULT_TOKEN: ${{ secrets.SEGFAULT_TOKEN }}
  SEGFAULT_INSTANCE: ${{ secrets.SEGFAULT_INSTANCE }}
jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            script.sh
      - name: Install expect
        run: |
          sudo apt update
          sudo apt-get install expect -y
      - name: Reboot Server
        run: |
          chmod +x restart.sh
          ./restart.sh ${{ secrets.SEGFAULT_TOKEN }}
      - name: Start Server
        run: |
          chmod +x script.sh
          ./script.sh ${{ secrets.SEGFAULT_TOKEN }}
